# -*- coding: utf-8 -*-
"""lab03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T45hGI6r9zqr3ZzKqh-NG_fZvUFUERcQ
"""


class Palavra():
    def __init__(self, palavra="a"):
        self.palavra = palavra

    def letrasCorretas(self, letras=""):
        return "".join([x+' ' if letras.find(x) >= 0 else "_ " for x in self.palavra])


class JogoDaForca():
    def __init__(self, palavra):
        self.palavra = Palavra(palavra)
        self.maxErros = 6
        self.letrasJogadas = ""
        self.letrasCorretas = ""
        self.letrasErradas = ""
        self.resultado = 'Você perdeu!'

    def jogo(self):
        status = self.jogar()
        newStatus = None

        while True:
            print(status)

            if self.maxErros <= 0:
                break
            elif status.find('_') < 0:
                self.resultado = 'Você ganhou!'
                break

            letra = input()
            self.letrasJogadas += letra
            newStatus = self.jogar()

            if newStatus == status:
                self.letrasErradas += (letra + " ")
                self.adicionaErro()
            else:
                self.printStatus()
                self.letrasCorretas += (letra + " ")
                status = newStatus

            print("Letras corretas: " + self.letrasCorretas)
            print("Letras erradas: " + self.letrasErradas)

        print(self.resultado)

    def jogar(self):
        return self.palavra.letrasCorretas(self.letrasJogadas)

    def adicionaErro(self):
        self.maxErros -= 1
        self.printStatus()

    def printStatus(self):
        if self.maxErros == 6:
            print("  +---+\n \
 |   |\n \
     |\n \
     |\n \
     |\n \
     |\n \
    _|_\n ")

        elif self.maxErros == 5:
            print("  +---+\n \
 |   |\n \
 0   |\n \
     |\n \
     |\n \
     |\n \
    _|_\n ")

        elif self.maxErros == 4:
            print("  +---+\n \
 |   |\n \
 0   |\n \
 |   |\n \
     |\n \
     |\n \
    _|_\n ")

        elif self.maxErros == 3:
            print("  +---+\n \
 |   |\n \
 0   |\n \
/|   |\n \
     |\n \
     |\n \
    _|_\n ")

        elif self.maxErros == 2:
            print("  +---+\n \
 |   |\n \
 0   |\n \
/|\  |\n \
     |\n \
     |\n \
    _|_\n ")

        elif self.maxErros == 1:
            print("  +---+\n \
 |   |\n \
 0   |\n \
/|\  |\n \
/    |\n \
     |\n \
    _|_\n ")

        else:
            print("  +---+\n \
 |   |\n \
 0   |\n \
/|\  |\n \
/ \  |\n \
     |\n \
    _|_\n ")

# p1 = Palavra('abc')
# p1.letrasCorretas('bc')


j1 = JogoDaForca('celular')
j1.jogo()
